Repository openscilab/parsipy, pull requests merged in 2025-03, with the labels that each got.

#10 Docstrings + README + minor edits
  AUTHORS.md
  MANIFEST.in
  README.md
  dev-requirements.txt
  parsipy/__init__.py
  parsipy/__main__.py
  parsipy/data.py
  parsipy/p2g.py
  parsipy/params.py
  parsipy/pipeline.py
  parsipy/pos_tagger.py
  parsipy/tokenizer.py
  parsipy/word_stemmer.py
  requirements.txt
  setup.py
Labels: documentation, enhancement

#11 Minor edits
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  README.md
  otherfiles/version_check.py
  parsipy/__init__.py
  parsipy/__main__.py
  parsipy/data.py
  parsipy/p2t.py
  parsipy/params.py
  parsipy/pipeline.py
  parsipy/pos_tagger.py
  parsipy/tokenizer.py
  parsipy/word_stemmer.py
  requirements.txt
Labels: documentation, test

#12 Version 0.1
  CHANGELOG.md
  autopep8.bat
  autopep8.sh
  parsipy/data.py
  parsipy/p2t.py
  parsipy/params.py
  parsipy/pipeline.py
  parsipy/pos_tagger.py
  parsipy/tokenizer.py
  parsipy/word_stemmer.py
Labels: release
