Repository openscilab/parsipy, pull requests merged in 2025-01, with the labels that each got.

#1 add POS tagger to pipeline
  Parsig_toolkit/.DS_Store
  Parsig_toolkit/.idea/workspace.xml
  Parsig_toolkit/embeddings.py
  Parsig_toolkit/main.py
  Parsig_toolkit/p2g.py
  Parsig_toolkit/pipeline.py
  Parsig_toolkit/pos_tagger.py
  Parsig_toolkit/roots.json
  Parsig_toolkit/stems_new.csv
  Parsig_toolkit/tokenizer.py
  Parsig_toolkit/word_stemmer.py
Labels: good first issue

#3 Structure
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  LICENSE
  SECURITY.md
Labels: documentation

#4 `setup.py`
  parsipy/__init__.py
  parsipy/__main__.py
  parsipy/embeddings.py
  parsipy/p2g.py
  parsipy/params.py
  parsipy/pipeline.py
  parsipy/pos_tagger.py
  parsipy/tokenizer.py
  parsipy/word_stemmer.py
  setup.py
Labels: enhancement

#5 Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  otherfiles/donation.png
  otherfiles/requirements-splitter.py
  otherfiles/version_check.py
Labels: documentation, enhancement

#6 Data
  MANIFEST.in
  parsipy/data.py
  parsipy/data/roots.json
  parsipy/data/stems.csv
  parsipy/p2g.py
  parsipy/word_stemmer.py
Labels: enhancement

#7 Refactor
  parsipy/__init__.py
  parsipy/p2g.py
  parsipy/params.py
  parsipy/pipeline.py
  parsipy/pos_tagger.py
  parsipy/tokenizer.py
  parsipy/word_stemmer.py
Labels: refactoring
